//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoulderGuide.Mobile.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoulderGuide.Mobile.Forms.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За приложението.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Катеренето е свобода. 
        ///
        ///Ние вярваме, че информацията за него също трябва да е свободна и свободно да се споделя.
        ///
        ///Разработването и преминаването на маршрут изискват усилен труд.
        ///
        ///Ние вярваме, че този труд трябва да бъде почетен. Всеки маршрут, който си е струвало да бъде изкатерен, си струва и да бъде споделен.
        ///
        ///Това приложение е израз на този стремеж за свобода. Целта му е да събере в себе си информация за Българските болдър обекти и маршрути и да я направи достъпна на всеки болдър ентусиаст..
        /// </summary>
        internal static string AboutInfo {
            get {
                return ResourceManager.GetString("AboutInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вие успешно деактивирахте разширеният режим..
        /// </summary>
        internal static string AdvancedModeDisabled {
            get {
                return ResourceManager.GetString("AdvancedModeDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вие успешно активирахте разширеният режим..
        /// </summary>
        internal static string AdvancedModeEnabled {
            get {
                return ResourceManager.GetString("AdvancedModeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разширени настройки.
        /// </summary>
        internal static string AdvancedOptions {
            get {
                return ResourceManager.GetString("AdvancedOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Достъп.
        /// </summary>
        internal static string AreaAccess {
            get {
                return ResourceManager.GetString("AreaAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настаняване.
        /// </summary>
        internal static string AreaAccommodations {
            get {
                return ResourceManager.GetString("AreaAccommodations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съдържание.
        /// </summary>
        internal static string AreaContent {
            get {
                return ResourceManager.GetString("AreaContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Етика.
        /// </summary>
        internal static string AreaEthics {
            get {
                return ResourceManager.GetString("AreaEthics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История.
        /// </summary>
        internal static string AreaHistory {
            get {
                return ResourceManager.GetString("AreaHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обща информация.
        /// </summary>
        internal static string AreaInfo {
            get {
                return ResourceManager.GetString("AreaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избраният сектор не е запазен на устройството или не може да бъде свален..
        /// </summary>
        internal static string AreaNotFoundOrCantBeDownloaded {
            get {
                return ResourceManager.GetString("AreaNotFoundOrCantBeDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ограничения.
        /// </summary>
        internal static string AreaRestrictions {
            get {
                return ResourceManager.GetString("AreaRestrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сектори.
        /// </summary>
        internal static string Areas {
            get {
                return ResourceManager.GetString("Areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтриване на локалните данни.
        /// </summary>
        internal static string ClearLocalData {
            get {
                return ResourceManager.GetString("ClearLocalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Катерачни обекти.
        /// </summary>
        internal static string ClimbingAreas {
            get {
                return ResourceManager.GetString("ClimbingAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добре.
        /// </summary>
        internal static string CloseDialog {
            get {
                return ResourceManager.GetString("CloseDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За контакти.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет от приложението Boulder Guide,
        ///
        ///....
        /// </summary>
        internal static string DefaultEmailBody {
            get {
                return ResourceManager.GetString("DefaultEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет от приложението Boulder Guide,
        ///
        ///....
        /// </summary>
        internal static string DefaultEmailSubject {
            get {
                return ResourceManager.GetString("DefaultEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инструменти на разработчика.
        /// </summary>
        internal static string DeveloperTools {
            get {
                return ResourceManager.GetString("DeveloperTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свали.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Филтър.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна неочаквана грешка. Моля да ни извините..
        /// </summary>
        internal static string GenericExceptionMessage {
            get {
                return ResourceManager.GetString("GenericExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка.
        /// </summary>
        internal static string GenericExceptionTitle {
            get {
                return ResourceManager.GetString("GenericExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интервал на опресняване на локацията (в секунди).
        /// </summary>
        internal static string GpsPollingInterval {
            get {
                return ResourceManager.GetString("GpsPollingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет!.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} маршрута в {1} сектора.
        /// </summary>
        internal static string HomeAreaInfoCountsFormat {
            get {
                return ResourceManager.GetString("HomeAreaInfoCountsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ.
        /// </summary>
        internal static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер на локалните данни.
        /// </summary>
        internal static string LocalStorageSizeInMB {
            get {
                return ResourceManager.GetString("LocalStorageSizeInMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добре.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При грешки.
        /// </summary>
        internal static string OnError {
            get {
                return ResourceManager.GetString("OnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна грешка при опита да се {0}. 
        ///Моля опитайте отново по-късно..
        /// </summary>
        internal static string OperationExceptionFormat {
            get {
                return ResourceManager.GetString("OperationExceptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подредба.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрити региони.
        /// </summary>
        internal static string PrivateAreas {
            get {
                return ResourceManager.GetString("PrivateAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повече ....
        /// </summary>
        internal static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Презареди.
        /// </summary>
        internal static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тази операция ще премахне свалените сектори..
        /// </summary>
        internal static string ReloadMessage {
            get {
                return ResourceManager.GetString("ReloadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Презареждане.
        /// </summary>
        internal static string ReloadTitle {
            get {
                return ResourceManager.GetString("ReloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трудност 6A-8C.
        /// </summary>
        internal static string RouteOrderByDifficulty {
            get {
                return ResourceManager.GetString("RouteOrderByDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трудност 8C-6A.
        /// </summary>
        internal static string RouteOrderByDifficultyDesc {
            get {
                return ResourceManager.GetString("RouteOrderByDifficultyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име А-Я.
        /// </summary>
        internal static string RouteOrderByName {
            get {
                return ResourceManager.GetString("RouteOrderByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име Я-А.
        /// </summary>
        internal static string RouteOrderByNameDesc {
            get {
                return ResourceManager.GetString("RouteOrderByNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маршрути.
        /// </summary>
        internal static string Routes {
            get {
                return ResourceManager.GetString("Routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търсене.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to изчистят локалните данни.
        /// </summary>
        internal static string UnableToClearLocalData {
            get {
                return ResourceManager.GetString("UnableToClearLocalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избраният сектор не е запазен на устройството.
        ///Няма интернет свързаност и той не може да бъде свален.
        ///Запазете секторът на устройството си за да е достъпен дори при липса на интернет връзка..
        /// </summary>
        internal static string UnableToDownloadArea {
            get {
                return ResourceManager.GetString("UnableToDownloadArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма интернет свързаност и секторът не може да бъде свален.
        ///Запазете секторът на устройството си за да е достъпен дори при липса на интернет връзка..
        /// </summary>
        internal static string UnableToDownloadEntireArea {
            get {
                return ResourceManager.GetString("UnableToDownloadEntireArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to свали локално сектор {0}.
        /// </summary>
        internal static string UnableToDownloadFormat {
            get {
                return ResourceManager.GetString("UnableToDownloadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избраният маршрут не е запазен на устройството.
        ///Няма интернет свързаност и той не може да бъде свален.
        ///Запазете секторът на устройството си за да е достъпен дори при липса на интернет връзка..
        /// </summary>
        internal static string UnableToDownloadRoute {
            get {
                return ResourceManager.GetString("UnableToDownloadRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to включи ранширеният режим.
        /// </summary>
        internal static string UnableToEnableAddvancedMode {
            get {
                return ResourceManager.GetString("UnableToEnableAddvancedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to въведе ключът..
        /// </summary>
        internal static string UnableToEnterKey {
            get {
                return ResourceManager.GetString("UnableToEnterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to филтрират секторите и маршрутите.
        /// </summary>
        internal static string UnableToFilter {
            get {
                return ResourceManager.GetString("UnableToFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to зареди сектор {0}.
        /// </summary>
        internal static string UnableToInitializeAreaFormat {
            get {
                return ResourceManager.GetString("UnableToInitializeAreaFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to зареди картата.
        /// </summary>
        internal static string UnableToInitializeMap {
            get {
                return ResourceManager.GetString("UnableToInitializeMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отвори екрана с настройките.
        /// </summary>
        internal static string UnableToInitializeSettings {
            get {
                return ResourceManager.GetString("UnableToInitializeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отвори екрана {0}.
        /// </summary>
        internal static string UnableToNavigateFormat {
            get {
                return ResourceManager.GetString("UnableToNavigateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отвори браузър с адрес &apos;{0}&apos;.
        /// </summary>
        internal static string UnableToOpenBrowserFormat {
            get {
                return ResourceManager.GetString("UnableToOpenBrowserFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отвори диалоговия прозорец.
        /// </summary>
        internal static string UnableToOpenDialog {
            get {
                return ResourceManager.GetString("UnableToOpenDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to стартира е-мейл клиентът.
        /// </summary>
        internal static string UnableToOpenEmailClient {
            get {
                return ResourceManager.GetString("UnableToOpenEmailClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to презаред информацията за катерачните обекти.
        /// </summary>
        internal static string UnableToReloadClimbingRegions {
            get {
                return ResourceManager.GetString("UnableToReloadClimbingRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сортират секторите и маршрутите.
        /// </summary>
        internal static string UnableToSort {
            get {
                return ResourceManager.GetString("UnableToSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уеб сайт.
        /// </summary>
        internal static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
    }
}
