//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoulderGuide.Mobile.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoulderGuide.Mobile.Forms.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Достъп.
        /// </summary>
        internal static string AreaAccess {
            get {
                return ResourceManager.GetString("AreaAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настаняване.
        /// </summary>
        internal static string AreaAccommodations {
            get {
                return ResourceManager.GetString("AreaAccommodations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съдържание.
        /// </summary>
        internal static string AreaContent {
            get {
                return ResourceManager.GetString("AreaContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Етика.
        /// </summary>
        internal static string AreaEthics {
            get {
                return ResourceManager.GetString("AreaEthics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История.
        /// </summary>
        internal static string AreaHistory {
            get {
                return ResourceManager.GetString("AreaHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обща информация.
        /// </summary>
        internal static string AreaInfo {
            get {
                return ResourceManager.GetString("AreaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избраният сектор не е запазен на устройството или не може да бъде свален..
        /// </summary>
        internal static string AreaNotFoundOrCantBeDownloaded {
            get {
                return ResourceManager.GetString("AreaNotFoundOrCantBeDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ограничения.
        /// </summary>
        internal static string AreaRestrictions {
            get {
                return ResourceManager.GetString("AreaRestrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сектори.
        /// </summary>
        internal static string Areas {
            get {
                return ResourceManager.GetString("Areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтриване на локалните данни.
        /// </summary>
        internal static string ClearLocalData {
            get {
                return ResourceManager.GetString("ClearLocalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Катерачни обекти.
        /// </summary>
        internal static string ClimbingAreas {
            get {
                return ResourceManager.GetString("ClimbingAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добре.
        /// </summary>
        internal static string CloseDialog {
            get {
                return ResourceManager.GetString("CloseDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свали.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Филтър.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интервал на опресняване на локацията (в секунди).
        /// </summary>
        internal static string GpsPollingInterval {
            get {
                return ResourceManager.GetString("GpsPollingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет!.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер на локалните данни.
        /// </summary>
        internal static string LocalStorageSizeInMB {
            get {
                return ResourceManager.GetString("LocalStorageSizeInMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подредба.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Презареди.
        /// </summary>
        internal static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трудност 6A-8C.
        /// </summary>
        internal static string RouteOrderByDifficulty {
            get {
                return ResourceManager.GetString("RouteOrderByDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трудност 8C-6A.
        /// </summary>
        internal static string RouteOrderByDifficultyDesc {
            get {
                return ResourceManager.GetString("RouteOrderByDifficultyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име А-Я.
        /// </summary>
        internal static string RouteOrderByName {
            get {
                return ResourceManager.GetString("RouteOrderByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име Я-А.
        /// </summary>
        internal static string RouteOrderByNameDesc {
            get {
                return ResourceManager.GetString("RouteOrderByNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маршрути.
        /// </summary>
        internal static string Routes {
            get {
                return ResourceManager.GetString("Routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търсене.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избраният сектор не е запазен на устройството.
        ///Няма интернет свързаност и той не може да бъде свален.
        ///Запазете секторът на устройството си за да е достъпен дори при липса на интернет връзка..
        /// </summary>
        internal static string UnableToDownloadArea {
            get {
                return ResourceManager.GetString("UnableToDownloadArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма интернет свързаност и секторът не може да бъде свален.
        ///Запазете секторът на устройството си за да е достъпен дори при липса на интернет връзка..
        /// </summary>
        internal static string UnableToDownloadEntireArea {
            get {
                return ResourceManager.GetString("UnableToDownloadEntireArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избраният маршрут не е запазен на устройството.
        ///Няма интернет свързаност и той не може да бъде свален.
        ///Запазете секторът на устройството си за да е достъпен дори при липса на интернет връзка..
        /// </summary>
        internal static string UnableToDownloadRoute {
            get {
                return ResourceManager.GetString("UnableToDownloadRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
