name: Publish Boulder Guide Android app

on:
  create:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --android=11.0

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Restore & Build
      run: msbuild ${{ github.workspace }}/src/BoulderGuide.Mobile.Forms/BoulderGuide.Mobile.Forms.Android/BoulderGuide.Mobile.Forms.Android.csproj /t:build /restore /t:PackageForAndroid /p:Configuration=Release /t:SignAndroidPackage

    - name: Upload Android Release to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.GDC_KEY }}
        packageName: com.lyuboasenov.boulder_guide
        releaseFiles: ${{ github.workspace }}/src/BoulderGuide.Mobile.Forms/BoulderGuide.Mobile.Forms.Android/bin/Release/*-Signed.apk
        track: beta
